//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_ControllerInput : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean RightTriggerAction
        {
            get
            {
                return SteamVR_Actions.controllerInput_RightTriggerAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTriggerAction
        {
            get
            {
                return SteamVR_Actions.controllerInput_LeftTriggerAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean ShowOverlayButton
        {
            get
            {
                return SteamVR_Actions.controllerInput_ShowOverlayButton;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ShowOverlayStick
        {
            get
            {
                return SteamVR_Actions.controllerInput_ShowOverlayStick;
            }
        }
    }
}
